export const API = {
  AUTH: '/v1/auth',
  USERS: 'utilisateurs',
  ELEVES: '/v1/eleves',
  PARENTS: '/v1/parents',
  ENSEIGNANTS: '/v1/enseignants',
  CLASSES: '/v1/classes',
  MATIERES: 'matieres',
  NOTES: 'notes',
  BULLETINS: 'bulletins',
  INSCRIPTIONS: 'inscriptions',
  PAIEMENTS: 'paiements',
  ABSENCES_ELEVE: '/v1/absences-eleves',
  ABSENCES_PERSONNEL: '/v1/absences-personnel',
  CONVOCATIONS: '/v1/convocations',
  ANNONCES: '/v1/annonces',
  ANNEES: '/v1/annees-academiques',
  BATIMENTS: '/v1/batiments',
  SALLES: '/v1/salles',
  COURS: '/v1/cours',
  CYCLES: '/v1/cycles',
  NIVEAUX: '/v1/niveaux',
  EMPLOIS: '/v1/emplois-du-temps',
  LIENS_BULLETIN: '/v1/liens-bulletin',
  LIENS_PAIEMENT: '/v1/liens-paiement',
  PERSONNEL: '/v1/personnel',
  POINTAGES: '/v1/pointages',
  RECLAMATIONS: 'reclamations',
  STATS: '/v1/stats/etablissement',
  PLATFORM: {
    TENANTS: '/platform/tenants',
    STATS: '/platform/stats',
    USERS: '/platform/utilisateurs',
    AUDIT: '/platform/audit-logs'
  }
} as const;
